### PR TITLE
Feature client dashboard view

### PR DESCRIPTION
**Pull request by devky690**
https://trello.com/c/eXDqaT5C

Just waiting client form view to be made, then we that is done will add further implemention to action event listener.

Some resources I used with this PR (helps with GUI designer)
-https://www.jetbrains.com/help/idea/getting-started.html

-https://www.jetbrains.com/help/idea/creating-listeners.html

Form Preview

### CODE REVIEW

**Review by Cwagne17 — COMMENTED** [review]
Looks good, could you attach a screenshot of what it looks like?

**Comment by Cwagne17** [comment]
I thought you were working on the client dashboard? The screen shot is of events?

**Review by Cwagne17 — CHANGES_REQUESTED** [review]
Turn into Client, from events

**Comment by devky690** [comment]
Preview Look and Feel

**Review by Cwagne17 — COMMENTED** [review]
How will we change the form so it can take data as a list and display it?

**Pull request merged**
